### ISSUE TITLE
Support for autoscaling based on traffic flow

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/http-add-on#350]
We should support the following traffic flows/types:

- [x] Ingress (*)
- [x] Service-to-service (*)
- [ ] https://github.com/kedacore/http-add-on/issues/6
- [ ] https://github.com/kedacore/http-add-on/issues/33

_(*) Current state as of Dec 2021 by using service interceptor & custom metric tracking_

**Comment by linkvt** [comment]
Closing as all subtasks are either implemented or closed as unplanned, nothing else to do here right now.
