### ISSUE TITLE
Roadmap to GA

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/http-add-on#911]
### Proposal

After the last months, we have improved a lot the add-on. In order to not lose the momentum, I'd like to define what we would expect from the add-on before considering it in GA, let's track all the features that we think are mandatory and nice to have. 

# Required
- [ ] Define the scope of the project for the mid/long term
- [ ] Active contributors/maintainers apart from us 
- [ ] Observability for all the components
- [ ] Websockets support
- [ ] KEDA's security standards (signing images, snyk, etc...)

# Nice to have
- [ ] Versioned docs
- [ ] Support for dedicated interceptors
- [ ] Load tests
- [ ] Support adding HTTP Triggers to user-managed ScaledObjects
- [ ] TLS Support

### Is this a feature you are interested in implementing yourself?

No

**Comment by Rohithzr** [comment]
I have installed the add-on on my test environment. Would be happy to contribute and test the add-on's functionality.

**Comment by tomkerkhove** [comment]
Docs are tracked in https://github.com/kedacore/keda-docs/issues/548

**Comment by ronaldpanape** [comment]
when is the estimated GA?

**Comment by JorTurFer** [comment]
> when is the estimated GA?

There isn't any estimated date, it depends on the contributors, we are working on features, but if there are contributions, the date for GA will be sooner

**Comment by linkvt** [comment]
Closing this issue in favor of the v1 milestone: https://github.com/kedacore/http-add-on/milestone/8 

All required issues from this list are implemented, we have a few more in the milestone. I would prefer releasing a stable v1 soon to get more adoption and get rid of the beta status.
Let me know if you disagree.
